spring:
  application:
    name: discovery-service
  config:
    import: "configserver:http://localhost:8888"

#spring.application.name=discovery-service
#
#server.port=8761
#
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false